// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRhE3Yn-vv4uRkKxUh3A3uV21g8hA7JbY',
    appId: '1:524636076490:web:837b16e53a8a1004993733',
    messagingSenderId: '524636076490',
    projectId: 'userapp-130f3',
    authDomain: 'userapp-130f3.firebaseapp.com',
    storageBucket: 'userapp-130f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmTJrtuszsj2wbLnl8oEeFtay9M5wwBiw',
    appId: '1:524636076490:android:a66d0188b2024255993733',
    messagingSenderId: '524636076490',
    projectId: 'userapp-130f3',
    storageBucket: 'userapp-130f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdl7K6ThOD0ghzzhFPi9gamrJI4S6rrX0',
    appId: '1:524636076490:ios:10aebb3909fe2a87993733',
    messagingSenderId: '524636076490',
    projectId: 'userapp-130f3',
    storageBucket: 'userapp-130f3.firebasestorage.app',
    iosBundleId: 'com.example.userAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdl7K6ThOD0ghzzhFPi9gamrJI4S6rrX0',
    appId: '1:524636076490:ios:10aebb3909fe2a87993733',
    messagingSenderId: '524636076490',
    projectId: 'userapp-130f3',
    storageBucket: 'userapp-130f3.firebasestorage.app',
    iosBundleId: 'com.example.userAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRhE3Yn-vv4uRkKxUh3A3uV21g8hA7JbY',
    appId: '1:524636076490:web:ae5d1f31d653eb93993733',
    messagingSenderId: '524636076490',
    projectId: 'userapp-130f3',
    authDomain: 'userapp-130f3.firebaseapp.com',
    storageBucket: 'userapp-130f3.firebasestorage.app',
  );
}
